Repository reactphp/socket, pull requests merged in 2019-01, with the labels that each got.

#185 Improve test suite to avoid some possible race conditions
  tests/FunctionalSecureServerTest.php
Labels: maintenance

#183 Improve performance by prefixing all global functions calls with \ to skip the look up and resolve process and go straight to the global function
  src/Connection.php
  src/Connector.php
  src/DnsConnector.php
  src/LimitingServer.php
  src/SecureConnector.php
  src/SecureServer.php
  src/Server.php
  src/StreamEncryption.php
  src/TcpConnector.php
  src/TcpServer.php
  src/UnixConnector.php
  src/UnixServer.php
Labels: easy pick, maintenance

#186 Improve TLS 1.3 support
  README.md
  composer.json
  src/Connection.php
  src/StreamEncryption.php
  tests/FunctionalSecureServerTest.php
Labels: bug, new feature

#188 Avoid possibility of missing remote address when TLS handshake fails
  src/SecureServer.php
  tests/SecureServerTest.php
Labels: bug, easy pick

#190 Example 99 improvements
  examples/99-generate-self-signed.php
Labels: easy pick, maintenance
