Repository reactphp/socket, pull requests merged in 2020-08, with the labels that each got.

#242 Change default socket backlog size to 511
  README.md
  src/TcpServer.php
  tests/FunctionalTcpServerTest.php
Labels: easy pick, new feature

#243 Update PHPUnit configuration schema for PHPUnit 9.3 and replace deprecated at() Mocks
  .gitattributes
  .travis.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/HappyEyeBallsConnectionBuilderTest.php
  tests/HappyEyeBallsConnectorTest.php
Labels: maintenance

#244 Fix possible `accept()` race condition when multiple socket servers listen on same socket address
  src/TcpServer.php
  src/UnixServer.php
  tests/TcpServerTest.php
  tests/UnixServerTest.php
Labels: bug

#246 Socket address of closed socket should be null (support PHP 8)
  src/Connection.php
Labels: easy pick, new feature

#245 Add full core team to the license
  LICENSE
  composer.json
Labels: maintenance
